### ISSUE TITLE
TS_HW TC0001 issue with VTMaK RTI

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_TestSuiteDevelopment#53]
Running TS_HW TC0001 the following messages are noticed in the log:

- turnInteractionsOn not implemented
- discoverObjectInstance not implemented

RTI issue, TS issue, or IVCT Framework issue?

**Comment by rhzg** [comment]
That's because the test case is using the default implementation for FederateAmbassador and that reports every methode which is not overwritten by some subclass. The test case should deal with that methods.

**Comment by bergtwvd** [comment]
Maybe this should be clarified in the message. It is in this case more `FOR INFO` than `WARN`?

**Comment by rhzg** [comment]
good question - I would say for messages a test case is receiving, but not actively processing, is worth a warning. I'm working on improving the message.

What currently worries me more is the fact, that the test case FAILS because it concludes the population counting is wrong (but only when running via Mak! It works fine for pitch and portico)

**Comment by rhzg** [comment]
Problem with the FAIL is fixed. The issue was that mak is calling a different version of the discoverObjectInstance, which was not implemented by the test case.
